version: "3.8"
services:
    db:
        image: mysql
        container_name: db_docker_florianmessu
        restart: always
        command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        volumes:
            - florianmessu-db-data:/var/lib/mysql
            - ./docker/mysql:/root
        environment:
            MYSQL_USER: 'symfony'
            MYSQL_PASSWORD: 'symfony'
            MYSQL_DATABASE: 'symfony'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        networks:
            - prod

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_florianmessu
        depends_on:
            - db
        ports:
            - "8082:80"
        environment:
            PMA_HOST: db
        networks:
            - prod

    www:
        build:
            context: ./
            dockerfile: ./docker/php/prod.Dockerfile
        container_name: www_docker_florianmessu
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.florianmessu.rule=Host(`florianmessu.fr`)"
            #      - "traefik.http.routers.florianmessu.rule=Host(`localhost`)"
            - "traefik.http.routers.florianmessu.entrypoints=websecure"
            - "traefik.http.routers.florianmessu.tls.certresolver=myresolver"
        networks:
            - prod
            - traefik

networks:
    prod:
    traefik:
        external: true
        name: traefik

volumes:
    florianmessu-db-data: